#Config file for TEAM07 car

import os

#PATHS
CAR_PATH = PACKAGE_PATH = os.path.dirname(os.path.realpath(__file__    ))
DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')

#VEHICLE
DRIVE_LOOP_HZ = 20
MAX_LOOPS = 100000

#CAMERA
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_RESOLUTION = (CAMERA_WIDTH, CAMERA_HEIGHT) #(width, height)
CAMERA_FRAMERATE = DRIVE_LOOP_HZ

#Controller MAX and MIN
OBJECT_MAX_ANGLE = 49.19
OBJECT_MIN_ANGLE = 0.0

OBJECT_MAX_DIST = CAMERA_HEIGHT
OBJECT_MIN_DIST = 80

OBJECT_NEED_SPEED_ONE = (CAMERA_HEIGHT / 3)
OBJECT_NEED_SPEED_ZERO = (CAMERA_HEIGHT / 3) * 2

#OBJECT Boundaries
LOWER_RED = (0, 80, 0)
UPPER_RED = (15, 255, 255)

#STEERING
STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 300
STEERING_RIGHT_PWM = 520
STEERING_STRAIGTH = (STEERING_LEFT_PWM + STEERING_RIGHT_PWM) / 2

#THROTTLE
THROTTLE_CHANNEL = 2
THROTTLE_FORWARD_PWM = 460
THROTTLE_STOPPED_PWM = 400
THROTTLE_REVERSE_PWM = 360
