#Config file for TEAM07 car

import os

#PATHS
CAR_PATH = PACKAGE_PATH = os.path.dirname(os.path.realpath(__file__    ))
DATA_PATH = os.path.join(CAR_PATH, 'data')
MODELS_PATH = os.path.join(CAR_PATH, 'models')

#VEHICLE
DRIVE_LOOP_HZ = 20
MAX_LOOPS = 100000

#CAMERA
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_RESOLUTION = (640, 480) #(width, height)
CAMERA_FRAMERATE = DRIVE_LOOP_HZ

#Controller MAX and MIN
OBJECT_MAX_ANGLE
OBJECT_MIN_ANGLE
OBJECT_MAX_DIST = 480
OBJECT_MIN_DIST = 

#OBJECT Boundaries
LOWER_RED = (0, 80, 0)
UPPER_RED = (15, 255, 255)

#STEERING
STEERING_CHANNEL = 1
STEERING_LEFT_PWM = 420
STEERING_RIGHT_PWM = 360

#THROTTLE
THROTTLE_CHANNEL = 0
THROTTLE_FORWARD_PWM = 400
THROTTLE_STOPPED_PWM = 360
THROTTLE_REVERSE_PWM = 310
